# Generated by Django 2.1.5 on 2021-08-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_auto_20210729_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
