# Generated by Django 2.1.5 on 2021-08-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_page_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='tag',
            field=models.CharField(default='none', max_length=24),
            preserve_default=False,
        ),
    ]
