# Generated by Django 2.1.5 on 2021-08-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_auto_20210804_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='tag',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
