# Generated by Django 2.1.5 on 2021-08-04 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rango', '0009_auto_20210804_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='page',
            name='likes',
        ),
        migrations.AddField(
            model_name='page',
            name='likes',
            field=models.ManyToManyField(related_name='page_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
