# Generated by Django 2.1.5 on 2021-08-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0013_auto_20210805_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.CharField(blank=True, choices=[('', ''), ('Beginner', 'beginner'), ('Junior Developer', 'junior'), ('Senior Developer', 'senior'), ('Professional', 'professional')], max_length=200),
        ),
    ]
