# Generated by Django 2.1.5 on 2021-08-05 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0014_userprofile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likecount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='page',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='page_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
