# Generated by Django 2.1.5 on 2021-08-05 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0015_auto_20210805_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likecount',
        ),
    ]
