# Generated by Django 2.1.5 on 2021-08-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0016_remove_comment_likecount'),
        ('rango', '0016_bookmarklist'),
    ]

    operations = [
    ]
