# Generated by Django 2.1.5 on 2021-08-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0017_merge_20210805_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarklist',
            name='page',
        ),
        migrations.AddField(
            model_name='bookmarklist',
            name='page',
            field=models.ManyToManyField(related_name='bookmark', to='rango.Page'),
        ),
    ]
