# Generated by Django 2.1.5 on 2021-08-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0018_auto_20210805_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmarklist',
            old_name='userprofile',
            new_name='user',
        ),
    ]
