# Generated by Django 2.1.5 on 2021-08-05 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rango', '0019_auto_20210805_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='bookmark',
            field=models.ManyToManyField(blank=True, default=None, related_name='fav', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookmarklist',
            name='page',
            field=models.ManyToManyField(related_name='bookmark_page', to='rango.Page'),
        ),
    ]
