# Generated by Django 2.1.5 on 2021-08-05 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0020_auto_20210805_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='_bookmark', to=settings.AUTH_USER_MODEL),
        ),
    ]
