# Generated by Django 2.1.5 on 2021-08-06 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0026_page_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarklist',
            name='page',
        ),
        migrations.RemoveField(
            model_name='bookmarklist',
            name='userprofile',
        ),
        migrations.DeleteModel(
            name='BookmarkList',
        ),
    ]
