# Generated by Django 2.1.5 on 2021-08-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0030_page_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='numberoflikes',
            field=models.IntegerField(default=0),
        ),
    ]
