# Generated by Django 2.1.5 on 2021-08-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0031_page_numberoflikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='numberoflikes',
        ),
    ]
